### ISSUE TITLE
Create accounts system on Starknet website

### ISSUE THREAD

**Issue by Wolk1618** [focustree/starkbot#2]
When the administrator of a server wants to add Starkbot to his server, he must go to the website, create an account and download / install the bot.

For the moment, the website is only a landing page where you can click to add the bot to your discord server.
We need to improve the website with : 
- replace "add to discord" button by : get ready with Starkbot
- a sign in page with classic options (I forgot my password, signup for new users, ...)
- all the logic of accounts creation and management
- once the user is signed in, he can download and install the bot on 3 different servers

There's only one different bot for each server to ensure data privacy for users (users from server A can't access to roles on the server B)

**Comment by onlydust-contributor** [comment]
@quentin-audinet is working on this contribution
OnlyDust link : https://app.onlydust.xyz/contributions/0x007e
