### ISSUE TITLE
Remove corresponding role to users when deleting a rule

### ISSUE THREAD

**Issue by Wolk1618** [focustree/starkbot#6]
For the moment, when a rule is deleted, the corresponding role is not removed to users.

We need to add an option to delete_rule command to ask the admin whether he wants to remove the roles to the users who got it or not.

**Comment by onlydust-contributor** [comment]
@gaetbout is working on this issue
OnlyDust link : https://app.onlydust.xyz/contributions/0x0081

**Comment by gaetbout** [comment]
Hey, 

Just made a PR for this issue.
Still more work required to finish the refactor.

🥷🤖
G.
